### ISSUE TITLE
Media folder in Storage/Root 🤔

### ISSUE THREAD

**Issue by adamkiss** [bnomei/kirby3-with-public-folder-kit#1]
Shouldn't be media here, and also in bnomei/kirby3-unittestkit be inside the media folder (via symlink to storage, or just there), so it's publically available? Kirby uses media folder to put generated (resized) and other stuff in, so if I don't think server (whether apache or nginx) can reach out of the public folder.

**Comment by bnomei** [comment]
yes. one could symlink it to the storage like i did [here](https://github.com/bnomei/kirby3-with-public-folder-kit/blob/master/public/index.php#L20) but i thought that would be a to much for a unittest setup.

moving the media to the storage imho only makes sense when the public folder setup is combined with automated deploys that require all non static code to be in storage folder. but thats not the case for this demo, right?

**Comment by adamkiss** [comment]
No no, what I mean:

```
root
|
|- content
|
|- …
|
|- media <-- this folder
|
|- public
|     |
|     |- media  <-- should be here, inside the /public?
|
|- storage
```

**Comment by bnomei** [comment]
sorry i messed it up with the unittestki in my head. i will check asap.

**Comment by bnomei** [comment]
**kirby3-with-public-folder-kit** is focused on automated deployments. so all non-static data in storage.
`public/media` symlinked to `storage/media`

**kirby3-unittestkit** is just a public folder setup aka index not at root level.
`public/media`
